version: "3.7"

services:
  duckhunt_bot:
    build: https://github.com/DuckHunt-discord/DHV4.git

    container_name: duckhunt_bot
    hostname: duckhunt_bot

    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      GLOBAL_API_KEY: ${GLOBAL_API_KEY}
      TOPGG_SHARED_SECRET: ${TOPGG_SHARED_SECRET}
      FATESLIST_API_TOKEN: ${FATESLIST_API_TOKEN}
      DISCORDBOTLIST_TOKEN: ${DISCORDBOTLIST_TOKEN}
      DISCORDBOTSGG_API_TOKEN: ${DISCORDBOTSGG_API_TOKEN}
      BOTSFORDISCORD_TOKEN: ${BOTSFORDISCORD_TOKEN}
      DISCORDBOATS_API_TOKEN: ${DISCORDBOATS_API_TOKEN}
      BOTLIST_SPACE_TOKEN: ${BOTLIST_SPACE_TOKEN}
      DISCORDEXTREMELIST_TOKEN: ${DISCORDEXTREMELIST_TOKEN}
      VOIDBOTS_TOKEN: ${VOIDBOTS_TOKEN}
      INFINITYBOTLIST_TOKEN: ${INFINITYBOTLIST_TOKEN}
      DB_HOST: "duckhunt_postgres"
      DB_USER: "duckhunt"
      DB_PASSWORD: "duckhunt"
      DB_NAME: "duckhunt"

    volumes:
      - duckhunt_cache:/bot/cache

    networks:
      - duckhunt

    depends_on:
      - duckhunt_postgres

    restart: unless-stopped

    logging:
      options:
        max-size: "1m"
        max-file: "3"

  duckhunt_website:
    build: https://github.com/DuckHunt-discord/DHV4_Web.git

    container_name: duckhunt_website
    hostname: duckhunt_website

    environment:
      SECRET_KEY: ${SECRET_KEY}
      DH_API_KEY: ${GLOBAL_API_KEY}
      DH_API_URL: "http://duckhunt_bot:8080/api"
      DB_HOST: "duckhunt_postgres"
      DB_USER: "duckhunt"
      DB_PASSWORD: "duckhunt"
      DB_NAME: "duckhunt"
      MEMCACHED_LOC: "duckhunt_cache:11211"

    volumes:
      - web_static:/static:rw

    networks:
      - duckhunt

    depends_on:
      - duckhunt_postgres
      - duckhunt_cache

    restart: unless-stopped

    logging:
      options:
        max-size: "1m"
        max-file: "3"

  duckhunt_proxy:
    image: caddy:2
    container_name: duckhunt_proxy
    hostname: duckhunt_proxy

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - $PWD/logs:/logs
      - caddy_local:/local:ro
      - web_static:/static:ro

    networks:
      - duckhunt

    restart: unless-stopped

    logging:
      options:
        max-size: "1m"
        max-file: "3"

  duckhunt_postgres:
    image: "postgres:12"

    container_name: duckhunt_postgres
    hostname: duckhunt_postgres

    environment:
      POSTGRES_USER: "duckhunt"
      POSTGRES_PASSWORD: "duckhunt"
      POSTGRES_DB: "duckhunt"
      POSTGRES_PORT: "5432"
      PGDATA: "/data/postgres"

    volumes:
      - postgres:/data/postgres

    ports:
      - "54320:5432"

    networks:
      - duckhunt

    restart: unless-stopped

    logging:
      options:
        max-size: "1m"
        max-file: "3"

  duckhunt_cache:
    image: "memcached"

    container_name: duckhunt_cache
    hostname: duckhunt_cache

    ports:
      - "11211:11211"

    entrypoint:
      - memcached
      - -m 128

    networks:
      - duckhunt

    restart: unless-stopped

  caddy_logparser:
    build: https://github.com/paris-ci/caddy-logparser.git

    container_name: caddy_logparser
    hostname: caddy_logparser

    volumes:
      - $PWD/logs:/logs
      - caddy_local:/local:rw

    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  caddy_local:
  postgres:
  duckhunt_cache:
  web_static:

networks:
  duckhunt:
